# Generated by Django 5.0.3 on 2024-05-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=108)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.CharField(max_length=256),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.ManyToManyField(to='api.movietype'),
        ),
    ]
