# Generated by Django 5.0.3 on 2024-05-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movietype_alter_movie_thumbnail_remove_movie_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
