# Generated by Django 5.0.3 on 2024-05-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_movie_type_movie_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieType',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
