# Generated by Django 5.0.3 on 2024-04-16 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
