# Generated by Django 5.0.3 on 2024-04-22 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.TextField(default=1, max_length=1080),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
