# Generated by Django 5.0.3 on 2024-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rating_created_at_rating_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True, max_length=1080),
        ),
    ]
