# Generated by Django 5.0.3 on 2024-04-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rating_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(max_length=1080),
        ),
    ]
